name: release.yml
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: "Compile"
        run: make
      - name: "Generate Release Message"
        run: make release_message
      - name: "Parse Release Timestamp"
        run: echo "TIMESTAMP=$(TZ='America/Chicago' date +"%Y/%m/%d-%T-cst")" >> ${GITHUB_ENV}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          bodyFile: "release.md"
          commit: '${{ github.sha }}'
          tag: 'release_${{ env.timestamp }}'