name: release.yml
on:
  push:
    branches: ["main"]

jobs:
  tag:
    name: Generate release tag from current time
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.parse.outputs.tag }}
    steps:
      - name: Parse time
        id: parse
        run: echo "TAG=$(TZ='America/Chicago' date +"%Y/%m/%d-%T-cst")" >> "$GITHUB_OUTPUT"
  build:
    name: Build for all applicable targets
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: ["tag"]
    steps:
      - uses: actions/checkout@v4
      - name: "Compile"
        run: make
      - name: "Generate Release Message"
        run: make release_message
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          bodyFile: "release.md"
          commit: '${{ github.sha }}'
          tag: '${{ steps.tag.outputs.tag }}'